<?php
/**
 * The Waiver & Release Agreement text, verbatim from the All Alpha Armory
 * site (Contact Form 7 "Wavier" form, ID 94061 in the archived store DB),
 * with export-mangled smart quotes / em-dashes restored. Do not reword
 * without counsel — this is the legal document the range actually uses.
 */
?>
<p style="margin-top:0"><b>ALL ALPHA ARMORY INC<br />TRIPLE A SPORTSMAN CLUB<br />Waiver &amp; Release Agreement (the &ldquo;Agreement&rdquo;)</b></p>

<p>ALL ALPHA ARMORY INC (&ldquo;Triple A&rdquo;), a Corporation organized under the laws of the State of Texas, with a primary business location at 2721 FM936, Hubbard, TX 76648.</p>

<p><b>Definitions.</b> For purposes of this Agreement: (i) &ldquo;Covered Locations&rdquo; means any and all real property, ranges, buildings, staging areas, show floors, parking lots, temporary sites, off-site venues, and any other locations where Triple A conducts, sponsors, attends, or participates in events or activities, including but not limited to gun shows, demonstrations, trainings, marketing events, deliveries, pickups, and off-premises operations, whether now known or hereafter used; (ii) &ldquo;Covered Property&rdquo; means any vehicles, trailers, mobile units, carts, lifts, generators, firearms, suppressors, ammunition, targets, tools, machinery, and equipment of any kind that are owned, leased, rented, loaned, operated, or otherwise controlled by Triple A; (iii) &ldquo;Activities&rdquo; means any firearm-related or Triple A-related activities, including without limitation handling, shooting, cleaning, transporting, loading/unloading, mounting/dismounting, demonstrations, training, set-up/tear-down, display, sales or marketing support, ride-alongs, or any other participation in or around the Covered Locations and/or the Covered Property; and (iv) &ldquo;Facilities&rdquo; collectively refers to the Covered Locations and the Covered Property.</p>

<p><b>Section 1. Waiver And Release.</b></p>

<p>In consideration for receiving permission from Triple A to access or use the Facilities and/or to participate in the Activities, Participant, on behalf of itself, its heirs, representatives, administrators, successors, and permitted assigns (collectively, the &ldquo;Participant Parties&rdquo;, and together with Participant, the &ldquo;Releasors&rdquo;), hereby voluntarily, knowingly, and expressly discharges, waives, and releases any and all causes of action, claims, complaints, demands, grievances, liabilities, rights, and suits (collectively, the &ldquo;Released Claims&rdquo;) &mdash; whether known or unknown, whether at law or in equity, whether in contract or in tort, whether at common law or by statute &mdash; that any of the Releasors had, has, or may have against Triple A, its affiliates, or any of their respective owners, members, managers, partners, directors, officers, employees, contractors, agents, invitees, or licensees (collectively, the &ldquo;Triple A Parties&rdquo;, and together with Triple A, the &ldquo;Releasees&rdquo;) as of the Effective Date, arising out of or relating to any damage, death, injury, or loss sustained by any person or property in connection with or as a result of any Participant&rsquo;s access to or use of the Facilities or participation in the Activities, regardless of location and regardless of whether such damage, death, injury, or loss is directly or indirectly caused, in whole or in part, by the negligence, gross negligence, or recklessness of any of the Releasees. Without limiting the foregoing, the Released Claims expressly include risks associated with or arising from contact with or operation of the Covered Property (e.g., riding in or on, mounting or dismounting, entering or exiting, loading or unloading vehicles, trailers, or machinery), slips, trips, and falls (including falls from vehicles or trailers), impacts or head injuries (including striking fixed or moving objects), moving parts, lifting and material handling, noise, blast, recoil, heat, and other hazards inherent in the Activities and the Facilities.</p>

<p><b>Section 2. Covenant Not To Sue.</b></p>

<p>In consideration for receiving permission from Triple A to access or use the Facilities and/or to participate in the Activities, each of the Releasors hereby voluntarily, knowingly, and expressly covenants not to assert or to participate in the assertion of any of the Released Claims against any of the Releasees on or after the Effective Date.</p>

<p><b>Section 3. Indemnification.</b></p>

<p>In consideration for receiving permission from Triple A to access or use the Facilities and/or to participate in the Activities, Participant hereby voluntarily, knowingly, and expressly indemnifies and holds harmless each of the Releasees from any and all costs, damages, expenses, liabilities, and losses &mdash; including, but not limited to, reasonable attorney&rsquo;s fees and court costs &mdash; incurred or sustained by any of the Releasees arising out of or relating to any Released Claims, Participant&rsquo;s access to or use of the Facilities, or Participant&rsquo;s participation in the Activities.</p>

<p><b>Section 4. Participant Representations.</b></p>

<p>In consideration for receiving permission from Triple A to access or use the Facilities and/or to participate in the Activities, Participant represents and warrants, as of the Effective Date, that:</p>

<p>(a) Participant acknowledges and agrees that: (i) accessing or using the Facilities and/or participating in the Activities is inherently dangerous and exposes Participant to known and unknown risks of damage, death, injury, or loss to the person or property of Participant; (ii) Triple A is not obligated to permit Participant to access or use the Facilities and/or to participate in the Activities; (iii) Triple A may, in its sole discretion and at any time, refuse or withdraw permission for Participant to access or remain within any Covered Location, to use any Covered Property, and/or to participate in the Activities for any reason or for no reason without providing any refund; (iv) conditions at the Facilities may prevent Participant from inspecting certain areas or components, and there may be risks that are unknown or unforeseeable to Participant; (v) the Activities are strenuous, dangerous, and require a certain degree of physical condition, ability, maturity, and skill; (vi) all releases in Section 1, all covenants in Section 2, all obligations in Section 3, and all representations in this Section 4 (A) are intended, and shall be construed, to be as broad and inclusive as permitted by the laws of the State of Texas, and (B) shall be deemed reaffirmed each time that Participant accesses or uses the Facilities and/or participates in the Activities; (vii) Participant has read and understood this Agreement and all safety rules and regulations (the &ldquo;Rules&rdquo;) annexed to this Agreement; and (viii) Triple A is reasonable in and is actually relying upon the representations and warranties contained in this Section 4.</p>

<p>(b) Participant voluntarily and knowingly: (i) chooses to access or use the Facilities and/or to participate in the Activities notwithstanding the existence of known and unknown risks of damage, death, injury, or loss; (ii) accepts and assumes any and all such risks, including but not limited to risks from vehicles, trailers, machinery, tools, loading/unloading, set-up/tear-down, mounting/dismounting, and falls (including falls from or around vehicles or elevated surfaces); (iii) waives any right of privacy, publicity, compensation, copyright, or other similar right to any photographs, film, or other images that Releasees may obtain of Participant at or within the Facilities and/or participating in the Activities; and (iv) consents to the use by Releasees of any such photographs, film, or other images.</p>

<p>(c) Participant covenants and agrees that Participant will: (i) continuously inspect for unsafe conditions any portion of the Facilities where Participant is located; (ii) immediately leave, and refuse to participate in any Activities that occur in, any area or around any Covered Property where an unsafe condition is present; (iii) promptly advise Triple A personnel of any unsafe conditions at the Facilities; and (iv) exercise safe firearm-handling and equipment-handling practices, and adhere to the Rules, while accessing or using the Facilities and/or participating in the Activities.</p>

<p>(d) Participant confirms and verifies that Participant: (i) either (A) is eighteen (18) years of age or older as of the Effective Date, or (B) is under eighteen (18) years of age as of the Effective Date and will be accompanied and supervised by a parent or legal guardian at all times while accessing or using the Facilities and/or participating in the Activities; (ii) has not been adjudicated as mentally defective, been voluntarily or involuntarily committed to a mental institution, or been diagnosed as having any mental illness; (iii) has not been the subject of any criminal or other proceeding that prevents Participant from legally owning, handling, or possessing a firearm in the State of Texas; (iv) is not currently under the influence of any alcohol, narcotic drug, or controlled substance; and (v) possesses the requisite physical condition, ability, maturity, and skill to properly and safely participate in the Activities.</p>

<p>(e) All information provided by Participant on the Safety Questionnaire, which is incorporated by reference herein, and all representations made by Participant in this Section 4, are true, accurate, and complete as of the Effective Date.</p>

<p><b>Section 5. Mandatory Arbitration.</b></p>

<p>(a) Any claim or dispute brought by or on behalf of the Participant relating to this Agreement, the Facilities, or the Activities &mdash; whether at law or in equity, whether in contract or in tort, whether at common law or by statute &mdash; shall be submitted to mediation and, if not settled during mediation, shall thereafter be submitted to binding arbitration (the &ldquo;Arbitration&rdquo;).</p>

<p>(b) Each party to the Arbitration shall pay its own attorney&rsquo;s fees and expenses, including but not limited to expert fees and costs of production of materials. Fees and expenses of the arbitrator shall be borne by the party initiating the Arbitration; provided that if such party prevails by the arbitrator&rsquo;s award, the other party shall be responsible for fees and expenses of the arbitrator. If the award recognizes validity to both parties&rsquo; actions, responsibility for fees and expenses of the arbitrator shall be apportioned by the arbitrator. If any party commences litigation in violation of this Section 5, such party shall reimburse the other parties to the litigation for their costs and expenses, including but not limited to attorney&rsquo;s fees incurred in seeking abatement of such litigation and enforcement of arbitration.</p>

<p>(c) The Arbitration award or decision is final and may be confirmed, entered, and enforced as a judgment in a court of competent jurisdiction, subject to appeal only in the event of the arbitrator&rsquo;s manifest disregard of the law, no evidence to support the award, or other such grounds for appeal of arbitration awards that exist by statute, common law, or the applicable rules of the administrative agency.</p>

<p>(d) IF IT IS DETERMINED THAT THE ARBITRATION PROVISIONS CONTAINED IN THIS PARAGRAPH 5 ARE NOT ENFORCEABLE, PARTICIPANT: (I) SUBMITS AND CONSENTS TO THE JURISDICTION OF ANY STATE OR FEDERAL COURT LOCATED IN LIMESTONE COUNTY, TEXAS; (II) ACKNOWLEDGES AND AGREES THAT ALL ACTIONS OR PROCEEDINGS ARISING OUT OF OR RELATING TO THIS AGREEMENT, THE FACILITIES, OR THE ACTIVITIES SHALL BE LITIGATED EXCLUSIVELY IN A STATE OR FEDERAL COURT LOCATED IN LIMESTONE COUNTY, TEXAS; AND (III) WAIVES (A) ANY DEFENSE OF FORUM NON CONVENIENS; AND (B) ANY RIGHT TO A JURY TRIAL. PARTICIPANT ACKNOWLEDGES THAT THIS SECTION 5(D) IS A MATERIAL INDUCEMENT TO TRIPLE A&rsquo;S ENTERING INTO THIS AGREEMENT.</p>

<p><b>Section 6. Miscellaneous.</b></p>

<p>(a) <b>No Waiver.</b> No amendment or waiver of any provision of this Agreement, and no consent to any departure therefrom by Triple A, shall be effective unless it is made in writing and signed by Triple A. Each such waiver or consent shall be effective only in the specific instance and for the specific purpose for which it is given. No failure or delay by Triple A in exercising any right, remedy, power, or privilege hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right, remedy, power, or privilege hereunder preclude any other or further exercise thereof or the exercise of any other right, remedy, power, or privilege. The rights, remedies, powers, and privileges provided herein are cumulative and not exclusive of any rights, remedies, powers, and privileges provided by law.</p>

<p>(b) <b>Successors and Assigns.</b> The provisions of this Agreement shall be binding upon and inure to the benefit of Releasees, Participant, and their respective successors and assigns permitted hereby; provided, however, that Participant may not assign or otherwise transfer any of its rights or obligations hereunder without the prior written consent of Triple A.</p>

<p>(c) <b>Merger, Integration, and No Reliance.</b> This Agreement, the Safety Questionnaire, and the Rules comprise the complete and integrated agreement of the parties hereto relating to Participant&rsquo;s access to or use of the Facilities and participation in the Activities, and supersede all prior written or verbal agreements, representations, warranties, inducements, understandings, and promises between the parties on such subject matter. In the event of any conflict, the provisions of this Agreement shall control. Participant acknowledges and agrees that no written or verbal agreements, representations, warranties, inducements, understandings, or promises that are not embodied in this Agreement and that relate to the subject matter hereof: (i) have been made by Triple A or anyone acting on its behalf; (ii) are being relied upon by Participant; or (iii) shall be binding on any of the Releasees.</p>

<p>(d) <b>Severability.</b> If any provision of this Agreement is held to be illegal, invalid, or unenforceable, then the legality, validity, and enforceability of the remaining provisions of this Agreement shall not be affected or impaired thereby. The invalidity of any provision in a particular jurisdiction shall not invalidate or render unenforceable such provision in any other jurisdiction.</p>

<p>(e) <b>Governing Law.</b> This Agreement shall be governed by, and construed in accordance with, the laws of the State of Texas without regard to any conflict of laws principles.</p>

<p>(f) <b>Limitation of Liability.</b> Under no circumstances shall any Releasee be liable to any Releasor for: (i) an amount greater than $1,000; or (ii) any special, indirect, consequential, exemplary, or punitive damages. Releasors voluntarily, knowingly, and expressly waive any and all rights to special, indirect, consequential, exemplary, and punitive damages. Any claim or cause of action arising out of or relating to this Agreement, the Facilities, or the Activities shall be barred unless it is brought within two (2) years following the Effective Date. Any longer periods of limitations are voluntarily, knowingly, and irrevocably waived by Releasors.</p>

<p>The undersigned hereby: (1) represents and warrants that Participant has read and understood all of the provisions contained in this Agreement; and (2) agrees to be bound by all of the terms and conditions contained in this Agreement.</p>
